### ISSUE TITLE
Random Number of Card

### ISSUE THREAD

**Issue by ChayathonPP** [ShinRunner1st/Project100#4]
#include <iostream>
#include <vector>
#include <cstdlib>
#include <ctime>
#include <string>
using namespace std;
enum Suit { HEARTS, SPADES, CLUBS, DIAMONDS };

struct Card {
    int value;
    Suit suit;
};

int random_int(int min, int max) {
    return rand() % (max - min + 1) + min;
}

Card draw_card(vector<Card>& deck, vector<Card>& hand) {
    int index = random_int(0, deck.size() - 1);
    Card card = deck[index];
    deck.erase(deck.begin() + index);
    hand.push_back(card);
    return card;
}

string ssuit(Suit suit) {
    switch (suit) {
        case HEARTS: return "\x03";
        case SPADES: return "\x06";
        case CLUBS: return "\x05";
        case DIAMONDS: return "\x04";
        default: return "unknown";
    }
}

string draw(Card card) {
    string value;
    switch (card.value) {
        case 1: value = "A"; break;
        case 2: value = "2"; break;
        case 3: value = "3"; break;
        case 4: value = "4"; break;
        case 5: value = "5"; break;
        case 6: value = "6"; break;
        case 7: value = "7"; break;
        case 8: value = "8"; break;
        case 9: value = "9"; break;
        case 10: value = "10"; break;
        case 11: value = "J"; break;
        case 12: value = "Q"; break;
        case 13: value = "K"; break;
        default: value = "unknown"; break;
    }
    return value + ssuit(card.suit);
}
void pick_a_card(int n) {
    vector<Card> deck;
    for (int value = 1; value <= 13; value++) {
        for (int suit = HEARTS; suit <= DIAMONDS; suit++) {
            deck.push_back({value, static_cast<Suit>(suit)});
        }
    }
    srand(time(nullptr)); 
    
    vector<Card> hand;
    for (int i = 1; i <= n; i++) {
        if (deck.size() == 0) {
            cout << "The deck is empty!" << endl;
            break;
        }
        Card card = draw_card(deck, hand);
        cout << "You drew the " << draw(card) << "." << endl;
    }
}

int main() {
    
   pick_a_card(2);
   

    }

**Comment by ShinRunner1st** [comment]
- ขอเปลี่ยน function randomcard เป็นสร้าง deck แล้ว shuffledeck (สุ่มเป็นเลข 0-51 ก่อนก็ได้แล้วค่อยมา format ให้แสดงเป็น รูปที่หลัง(อันนี้งานของคนทำ graphic)) แทนแล้วให้เก็บค่าเป็น vector หรือ array deck แทน แล้วเวลาจะใช้ drawcard ก็แค่ให้ push ค่าออกมา (push เป็นตัวแรก ของเด็คแล้วค่อย erase ค่านั้นที่หลังก็ได้)
- และก็ อย่าพึ่งทำ function ที่ showcard (ที่มัน return เป็น string) มาเดี๋ยวมันจะ hard coded แล้วคนที่ทำ graphic กับ ai มันจะเอาค่าที่ return ออกมาไปใช้ต่อไม่ได้

- สรุปคือ ตอนนี้ขอแค่ function สร้างเด็ค, สลับไพ่, ดึงไพ่ออกมาจากเด็ค ก่อน (อย่า return เป็น string มันเอาไปใช้ต่อไม่ได้)

**Comment by ShinRunner1st** [comment]
แล้วก็ใช้ class แทน sturct ได้ก็ดี ถ้ามั่นใจว่าโอเคแล้ว commit เป็น ไฟล์ header (.h) มาได้เลยก็ได้เดี๋ยวช่วยดูให้

**Comment by ChayathonPP** [comment]
#include <iostream>
#include <cstdlib>
#include <ctime>
#include <vector>
#include <algorithm>

using namespace std;

int getRandomNumber() 
{
    static vector<int> generatedNumbers;
    int randomNum;
    srand(time(0));
    do {
        randomNum = rand() % 52;
    } while (find(generatedNumbers.begin(), generatedNumbers.end(), randomNum) != generatedNumbers.end());
    generatedNumbers.push_back(randomNum);
    return randomNum;
}

int main() 
{
    string number[13]={"A","2","3","4","5","6","7","8","9","10","J","K","Q"};
    string suit[4]={"\x03","\x04","\x05","\x06"};
    string card[52];
    int index = 0;

for(int i=0 ; i<13 ; i++)
{
     for(int j=0;j<4;j++)
     {
       card[index] = number[i] + suit[j];
       index++;
     }
}
  cout << card[getRandomNumber()]<<"\n";
    return 0;
}
