### ISSUE TITLE
Draw Card

### ISSUE THREAD

**Issue by ChayathonPP** [ShinRunner1st/Project100#5]
#include <iostream>
#include <cstdlib>
#include <ctime>
#include <vector>
#include <algorithm>

using namespace std;

int getRandomNumber() 
{
    static vector<int> generatedNumbers;
    int randomNum;
    srand(time(0));
    do {
        randomNum = rand() % 52;
    } while (find(generatedNumbers.begin(), generatedNumbers.end(), randomNum) != generatedNumbers.end());
    generatedNumbers.push_back(randomNum);
    return randomNum;
}

int main() 
{
    string number[13]={"A","2","3","4","5","6","7","8","9","10","J","K","Q"};
    string suit[4]={"\x03","\x04","\x05","\x06"};
    string card[52];
    int index = 0;

for(int i=0 ; i<13 ; i++)
{
     for(int j=0;j<4;j++)
     {
       card[index] = number[i] + suit[j];
       index++;
     }
}
  cout << card[getRandomNumber()]<<"\n";

  
  
    
    return 0;
}

**Comment by ShinRunner1st** [comment]
เขียนระบบต่อเลยทำ flowchart ไว้ให้ในคอมเม้นละ #1 
AI เสร็จละ ศึกษาข้อมูลในโค้ดได้เลย
